aliases:
    fleeks: cd ~/.local/share/fleek
allow_broken: false
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - htop
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      home: ""
      hostname: fedora
      os: linux
      username: danil
track: nixos-unstable
unfree: true
users:
    - email: antoshindanil@ya.ru
      name: danil
      ssh_private_key_file: ~/.ssh/id_ed25519
      ssh_public_key_file: ~/.ssh/id_ed25519.pub
      username: danil
